### ISSUE TITLE
A Serious Problem In Your Model

### ISSUE THREAD

**Issue by ZephyrChenzf** [WING-NUS/sequicity#13]
There is a serious problem here. In your model, the generated reply is used as the input for the next round. When testing, you should use the generated response, and you directly use the existing reply of the training data. This is wrong.

**Comment by shizhediao** [comment]
Yes, it's true.
The reason is our baseline (NNDIAL, https://github.com/shawnwun/NNDIAL) did so. In consideration of comparing, we have no choice.
