### ISSUE TITLE
Why does function _extract_request() in metric.py use EOS_Z1 as end mark instead of EOS_Z2?

### ISSUE THREAD

**Issue by hejunqing** [WING-NUS/sequicity#15]
As processed in _get_tokenized_data() in reader.py, requested bspans are ended with 'EOS_Z2' and appended to informable bspans in _encode_data(). That means the generated_bspan are ended with EOS_Z2.
However, in metrics.py,  the codes in _extract_request() function are using 'EOS_Z1' to truncate the generated bspan. e.g., in line 168.
Why? I am quite confused.

**Comment by AuCson** [comment]
Hi hejunqing,
Thanks for your question. Extract_request is not used in this code. As described in our paper, the match rate metric is determined by "extracted constraints", and success F1 and BLEU scores are determined by generated responses.  Thanks for reminding and we will soon clear these dead code.

**Comment by AuCson** [comment]
Hi hejunqing,
I reviewed the code and found the code snippet you just mentioned:    
```
def _extract_request(self, z):
        z = z.split()
        if 'EOS_Z1' not in z or z[-1] == 'EOS_Z1':
            return set()
        else:
            idx = z.index('EOS_Z1')
            return set(z[idx+1:])
```
The belief span is in the form of "constraint1, constraint2, ..., EOS_Z1, request1, request2, ..., EOS_Z2".
Therefore we should identify request slot after an EOS_Z1. If no EOS_Z1 is decoded, we regard it as no  request has been decoded. So the code logic is correct (although this code snippet does not participate in evaluation).

Hope this has solved your concern.
