### ISSUE TITLE
Something about the data in kvret

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [WING-NUS/sequicity#16]
Thanks for you open-source code.
I found it is very strange that the second turn's input for the model is the response of the agent on the last turn, which makes me confused.
Can you show me more information ?
Thank you very much !

**Comment by gmftbyGMFTBY** [comment]
I get the answer from the paper ...

**Comment by AuCson** [comment]
Hi,

Thanks for your question. According to our paper, the input of the model is the concatenation of the response of the previous turn and the user input of current turn. We have followed our baseline https://github.com/shawnwun/NNDIAL, and we believe it is a standard practice.
