### ISSUE TITLE
two questions about reader.py

### ISSUE THREAD

**Issue by mise42** [WING-NUS/sequicity#6]
1. in `read.py` **line 671**, `dial_turn['scenario']['kb']['items']` should be `raw_dial['scenario']['kb']['items]`, right?
2. in some dialogue like **line 448 to line 497** in `data/kvret/kvret_train_public.json`, `raw_dial['scenario']['kb']['items]` is `null`, so it will cause errors in method `KvReader.db_degree`

**Comment by shizhediao** [comment]
#7 has fixed the reader.py to run kvret dataset correctly.

**Comment by knmnyn** [comment]
Closing with #7 already merged.
