### ISSUE TITLE
The content in the tokenized kvret files seems to be wrong

### ISSUE THREAD

**Issue by se4u** [WING-NUS/sequicity#8]
I have two questions about the `kvret/*.tokenized.json` files.

### Why are all "requested" fields empty in these files ?

All `requested` fields seem to contain only the `EOS_Z2` token in the requested field ? This seems to be wrong ? At least some of the dialogues have actual requested slots in the kvret dataset.

``` python
>> print(frozenset([e3 for e1 in json.load(open('train.tokenized.json')) 
                       for e2 in e1 for e3 in e2['requested']]))

frozenset({'EOS_Z2'})
```

### Why aren't the constraints changing as the dialogue progresses ?

Consider the first dialogue `dial_id: 0` about directions to parking garage in `kvret/train.tokenized.json`. For all the turns in that dialogue the constraint set remains the same 
`"constraint": [ "parking",   "garage",     "EOS_Z1" ]` but the user asks to avoid heavy traffic in the next turn. This should change the constraints right ?

**Comment by ghost** [comment]
run 'python model.py -mode train -model tsdf-kvret' 
FileNotFoundError: [Errno 2] No such file or directory: './data/kvret/test.bspan.pkl'
Why? how to solve this problem?

**Comment by shizhediao** [comment]
@CrazyBirdWu The problem has been solved

**Comment by shizhediao** [comment]
@se4u kvret/*.tokenized.json are useless because we do not use these files in our code.
Please check it thanks!
